#!/usr/bin/env bash
# sadWatcher Installer
# https://github.com/horamsafaryani/sadWatcher

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

INSTALL_DIR="/var/lib/sadWatcher"
SERVICE_NAME="sadWatcher"
BINARY_NAME="sadWatcher"
GITHUB_REPO="horamsafaryani/sadWatcher"

# ─── helpers ──────────────────────────────────────────────────────────────────

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

ask() {
    local prompt="$1"
    local default="$2"
    local answer
    if [[ -n "$default" ]]; then
        read -rp "$(echo -e "${BOLD}$prompt${NC} [${default}]: ")" answer
        echo "${answer:-$default}"
    else
        read -rp "$(echo -e "${BOLD}$prompt${NC}: ")" answer
        echo "$answer"
    fi
}

check_root() {
    [[ "$EUID" -eq 0 ]] || error "Please run as root"
}

# ─── banner ───────────────────────────────────────────────────────────────────

banner() {
echo -e "${CYAN}"
cat << 'EOF'

▄██████░▄████▄░██████▄░██░██░██░▄████▄░████████░▄█████░██░░░██░▄█████░█████▄
██░░░░░░██░░██░██░░░██░██░██░██░██░░██░░░░██░░░░██░░░░░██░░░██░██░░░░░██░░██
▀█████▄░██░░██░██░░░██░██░██░██░██░░██░░░░██░░░░██░░░░░███████░█████░░█████▀
░░░░░██░██████░██░░░██░██░██░██░██████░░░░██░░░░██░░░░░██░░░██░██░░░░░██░░██
██████▀░██░░██░██████▀░▀██▀▀██▀░██░░██░░░░██░░░░▀█████░██░░░██░▀█████░██░░██

EOF
echo -e "${NC}"
echo -e "${BOLD}sadWatcher — Rebecca/Pasarguard/Marzban Traffic Overage Watcher${NC}"
echo -e "Kills xray connections instantly when users exceed their data limit\n"
}

# ─── uninstall ────────────────────────────────────────────────────────────────

uninstall() {
    info "Stopping and disabling service..."
    systemctl stop "$SERVICE_NAME" 2>/dev/null || true
    systemctl disable "$SERVICE_NAME" 2>/dev/null || true
    rm -f "/etc/systemd/system/${SERVICE_NAME}.service"
    systemctl daemon-reload
    info "Removing files..."
    rm -rf "$INSTALL_DIR"
    success "sadWatcher uninstalled."
    exit 0
}

# ─── main install ─────────────────────────────────────────────────────────────

install() {
    banner
    check_root

    echo -e "${BOLD}Welcome! Let's configure sadWatcher.${NC}\n"

    # ── q & a ────────────────────────────────────────────────────────────────

    DB_PATH=$(ask "Path to Rebecca/Pasarguard/Marzban SQLite database" "/var/lib/rebecca/db.sqlite3")

    BOUNCE_PORTS_INPUT=$(ask "xray ports to watch (comma separated)" "8080,8880")

    BOUNCE_PORTS="${BOUNCE_PORTS_INPUT// /}"

    CHECK_INTERVAL=$(ask "Check interval in seconds" "5")

    LOG_LEVEL=$(ask "Log level (DEBUG/INFO/WARNING/ERROR)" "INFO")

    echo ""
    info "Summary:"
    echo -e "  DB path       : ${CYAN}${DB_PATH}${NC}"
    echo -e "  Ports         : ${CYAN}${BOUNCE_PORTS}${NC}"
    echo -e "  Check interval: ${CYAN}${CHECK_INTERVAL}s${NC}"
    echo -e "  Install dir   : ${CYAN}${INSTALL_DIR}${NC}"
    echo -e "  Log file      : ${CYAN}${INSTALL_DIR}/sadWatcher.log${NC}"
    echo ""

    read -rp "$(echo -e "${BOLD}Proceed with installation? [Y/n]:${NC} ")" confirm
    confirm="${confirm:-Y}"
    [[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }

    # ── binary files  ─────────────────────────────────────────────────────────

    echo ""
    info "Creating install directory..."
    mkdir -p "$INSTALL_DIR"

    info "Downloading sadWatcher binary..."
    
    LATEST_URL="https://github.com/${GITHUB_REPO}/releases/latest/download/${BINARY_NAME}"

    if command -v curl &>/dev/null; then
        curl -fsSL "$LATEST_URL" -o "${INSTALL_DIR}/${BINARY_NAME}" || error "Download failed"
    elif command -v wget &>/dev/null; then
        wget -q "$LATEST_URL" -O "${INSTALL_DIR}/${BINARY_NAME}" || error "Download failed"
    else
        error "Neither curl nor wget found. Please install one."
    fi

    chmod +x "${INSTALL_DIR}/${BINARY_NAME}"
    success "Binary downloaded to ${INSTALL_DIR}/${BINARY_NAME}"

    # ── read .env ────────────────────────────────────────────────────────────

    info "Writing .env config..."
    cat > "${INSTALL_DIR}/.env" << EOF
# sadWatcher Configuration
# Generated by installer on $(date)

DB_PATH=${DB_PATH}
CHECK_INTERVAL=${CHECK_INTERVAL}
BOUNCE_PORTS=${BOUNCE_PORTS}
LOG_FILE=${INSTALL_DIR}/sadWatcher.log
LOG_LEVEL=${LOG_LEVEL}
EOF
    success ".env written to ${INSTALL_DIR}/.env"

    # ── systemd service ───────────────────────────────────────────────────────

    info "Creating systemd service..."
    cat > "/etc/systemd/system/${SERVICE_NAME}.service" << EOF
[Unit]
Description=sadWatcher — xray traffic overage watcher
After=network.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/${BINARY_NAME}
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable "$SERVICE_NAME"
    systemctl start "$SERVICE_NAME"

    success "Service created and started"

    # ── finall ─────────────────────────────────────────────────────────────────

    echo ""
    echo -e "${GREEN}${BOLD}✓ sadWatcher installed successfully!${NC}\n"
    echo -e "Useful commands:"
    echo -e "  ${CYAN}systemctl status ${SERVICE_NAME}${NC}       — check status"
    echo -e "  ${CYAN}journalctl -fu ${SERVICE_NAME}${NC}         — live logs"
    echo -e "  ${CYAN}tail -f ${INSTALL_DIR}/sadWatcher.log${NC}  — log file"
    echo -e "  ${CYAN}nano ${INSTALL_DIR}/.env${NC}               — edit config"
    echo -e "  ${CYAN}bash install.sh uninstall${NC}              — uninstall"
    echo ""
}

# ─── entry point ──────────────────────────────────────────────────────────────

case "${1:-install}" in
    install)   install ;;
    uninstall) check_root; uninstall ;;
    *)         echo "Usage: $0 [install|uninstall]"; exit 1 ;;
esac
